apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: shopmicro
type: Opaque
stringData:
  RABBITMQ_PASSWORD: shopmicro-pass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: shopmicro
data:
  RABBITMQ_HOST: message-queue
  RABBITMQ_USER: shopmicro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: shopmicro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: shopmicro/notification-service:1.0.0
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: notification-service-config
            - secretRef:
                name: notification-service-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 8
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: shopmicro
spec:
  selector:
    app: notification-service
  ports:
    - port: 5000
      targetPort: 5000

