apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: shopmicro
type: Opaque
stringData:
  rabbitmq-password: shopmicro-pass
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: shopmicro
data:
  RABBITMQ_DEFAULT_USER: shopmicro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-queue
  namespace: shopmicro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-queue
  template:
    metadata:
      labels:
        app: message-queue
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: rabbitmq-config
                  key: RABBITMQ_DEFAULT_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: rabbitmq-password
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 20
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: message-queue
  namespace: shopmicro
spec:
  selector:
    app: message-queue
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672

