apiVersion: v1
kind: Secret
metadata:
  name: product-service-secret
  namespace: shopmicro
type: Opaque
stringData:
  DB_PASSWORD: products_pass123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
  namespace: shopmicro
data:
  APP_VERSION: "1.1.0"
  DB_HOST: db-products
  DB_NAME: products_db
  DB_USER: products_user
  REDIS_HOST: cache
  REDIS_PORT: "6379"
  REDIS_TTL: "60"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: shopmicro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: shopmicro/product-service:1.1.0
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secret
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 8
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: shopmicro
spec:
  selector:
    app: product-service
  ports:
    - port: 5000
      targetPort: 5000
